export type TripTag =
  | "Beach"
  | "City"
  | "Nature"
  | "Culture"
  | "Food"
  | "Nightlife"
  | "Adventure"
  | "Romantic"
  | "Family"
  | "Budget"
  | "Luxury";

export type Destination = {
  id: string;
  city: string;
  country: string;
  countryCode: string;
  airportCode: string;
  region: string;
  latitude: number;
  longitude: number;
  tags: TripTag[];
  recommendedTripDays: [number, number];
  stayCostLow: number;
  stayCostHigh: number;
  localDailyCostLow: number;
  localDailyCostHigh: number;
  seasonTags: string[];
  popularityScore: number;
  shortDescription: string;
  image: string;
  imageAlt: string;
  imageCredit?: string;
};

export type VisaStatus =
  | "visa_free"
  | "eta"
  | "visa_on_arrival"
  | "evisa"
  | "visa_required"
  | "unknown";

export type VisaRule = {
  passportCountry: "UK" | "India";
  destinationCountryCode: string;
  status: VisaStatus;
  maxStayDays: number | null;
  officialSourceUrl: string;
  lastVerifiedAt: string;
};

export type FlightCache = {
  origin: string;
  destinationAirportCode: string;
  low: number;
  high: number;
  cachedAt: string;
};

export const passports = ["India", "UK"] as const;

export const origins = [
  "New York",
  "London",
  "Delhi",
  "Mumbai",
  "Toronto",
  "Sydney",
] as const;

export const tripTags: TripTag[] = [
  "Beach",
  "City",
  "Nature",
  "Culture",
  "Food",
  "Nightlife",
  "Adventure",
  "Romantic",
  "Family",
  "Budget",
  "Luxury",
];

const destinationRecords: Array<
  Omit<Destination, "image" | "imageAlt" | "imageCredit">
> = [
  {
    id: "tokyo",
    city: "Tokyo",
    country: "Japan",
    countryCode: "JP",
    airportCode: "TYO",
    region: "East Asia",
    latitude: 35.6762,
    longitude: 139.6503,
    tags: ["City", "Food", "Culture", "Family"],
    recommendedTripDays: [5, 9],
    stayCostLow: 95,
    stayCostHigh: 160,
    localDailyCostLow: 55,
    localDailyCostHigh: 95,
    seasonTags: ["spring", "autumn"],
    popularityScore: 98,
    shortDescription:
      "Dense neighborhoods, excellent transit, food markets, temples, and modern city energy.",
  },
  {
    id: "bangkok",
    city: "Bangkok",
    country: "Thailand",
    countryCode: "TH",
    airportCode: "BKK",
    region: "Southeast Asia",
    latitude: 13.7563,
    longitude: 100.5018,
    tags: ["City", "Food", "Nightlife", "Budget"],
    recommendedTripDays: [4, 8],
    stayCostLow: 45,
    stayCostHigh: 95,
    localDailyCostLow: 28,
    localDailyCostHigh: 55,
    seasonTags: ["winter", "shoulder"],
    popularityScore: 97,
    shortDescription:
      "Street food, temples, river ferries, markets, and a strong value-for-money base.",
  },
  {
    id: "mexico-city",
    city: "Mexico City",
    country: "Mexico",
    countryCode: "MX",
    airportCode: "MEX",
    region: "North America",
    latitude: 19.4326,
    longitude: -99.1332,
    tags: ["City", "Culture", "Food", "Budget"],
    recommendedTripDays: [4, 7],
    stayCostLow: 55,
    stayCostHigh: 110,
    localDailyCostLow: 32,
    localDailyCostHigh: 65,
    seasonTags: ["spring", "autumn", "winter"],
    popularityScore: 96,
    shortDescription:
      "Museums, architecture, markets, and world-class food with comparatively moderate daily costs.",
  },
  {
    id: "cancun",
    city: "Cancun",
    country: "Mexico",
    countryCode: "MX",
    airportCode: "CUN",
    region: "Caribbean",
    latitude: 21.1619,
    longitude: -86.8515,
    tags: ["Beach", "Family", "Nightlife", "Luxury"],
    recommendedTripDays: [4, 7],
    stayCostLow: 85,
    stayCostHigh: 190,
    localDailyCostLow: 45,
    localDailyCostHigh: 95,
    seasonTags: ["winter", "spring"],
    popularityScore: 93,
    shortDescription:
      "A beach-forward base for resorts, nightlife, and day trips to the Riviera Maya.",
  },
  {
    id: "lisbon",
    city: "Lisbon",
    country: "Portugal",
    countryCode: "PT",
    airportCode: "LIS",
    region: "Europe",
    latitude: 38.7223,
    longitude: -9.1393,
    tags: ["City", "Culture", "Food", "Romantic"],
    recommendedTripDays: [4, 7],
    stayCostLow: 85,
    stayCostHigh: 155,
    localDailyCostLow: 45,
    localDailyCostHigh: 80,
    seasonTags: ["spring", "autumn"],
    popularityScore: 95,
    shortDescription:
      "Tile-lined streets, viewpoints, seafood, trams, and easy day trips to Sintra or Cascais.",
  },
  {
    id: "barcelona",
    city: "Barcelona",
    country: "Spain",
    countryCode: "ES",
    airportCode: "BCN",
    region: "Europe",
    latitude: 41.3874,
    longitude: 2.1686,
    tags: ["Beach", "City", "Culture", "Nightlife"],
    recommendedTripDays: [4, 7],
    stayCostLow: 105,
    stayCostHigh: 190,
    localDailyCostLow: 55,
    localDailyCostHigh: 95,
    seasonTags: ["spring", "summer", "autumn"],
    popularityScore: 96,
    shortDescription:
      "Gaudi architecture, beaches, tapas, late nights, and walkable neighborhoods.",
  },
  {
    id: "rome",
    city: "Rome",
    country: "Italy",
    countryCode: "IT",
    airportCode: "ROM",
    region: "Europe",
    latitude: 41.9028,
    longitude: 12.4964,
    tags: ["City", "Culture", "Food", "Romantic"],
    recommendedTripDays: [4, 7],
    stayCostLow: 100,
    stayCostHigh: 180,
    localDailyCostLow: 55,
    localDailyCostHigh: 95,
    seasonTags: ["spring", "autumn"],
    popularityScore: 95,
    shortDescription:
      "Ancient sites, piazzas, trattorias, churches, and classic city-break appeal.",
  },
  {
    id: "paris",
    city: "Paris",
    country: "France",
    countryCode: "FR",
    airportCode: "PAR",
    region: "Europe",
    latitude: 48.8566,
    longitude: 2.3522,
    tags: ["City", "Culture", "Food", "Romantic", "Luxury"],
    recommendedTripDays: [4, 7],
    stayCostLow: 125,
    stayCostHigh: 230,
    localDailyCostLow: 65,
    localDailyCostHigh: 120,
    seasonTags: ["spring", "autumn", "winter"],
    popularityScore: 97,
    shortDescription:
      "Museums, cafes, landmarks, neighborhoods, and high cultural density.",
  },
  {
    id: "athens",
    city: "Athens",
    country: "Greece",
    countryCode: "GR",
    airportCode: "ATH",
    region: "Europe",
    latitude: 37.9838,
    longitude: 23.7275,
    tags: ["City", "Culture", "Food", "Budget"],
    recommendedTripDays: [4, 7],
    stayCostLow: 75,
    stayCostHigh: 140,
    localDailyCostLow: 42,
    localDailyCostHigh: 75,
    seasonTags: ["spring", "autumn"],
    popularityScore: 91,
    shortDescription:
      "Ancient history, lively neighborhoods, Greek food, and ferry connections.",
  },
  {
    id: "istanbul",
    city: "Istanbul",
    country: "Turkey",
    countryCode: "TR",
    airportCode: "IST",
    region: "Europe / Asia",
    latitude: 41.0082,
    longitude: 28.9784,
    tags: ["City", "Culture", "Food", "Budget"],
    recommendedTripDays: [4, 7],
    stayCostLow: 55,
    stayCostHigh: 120,
    localDailyCostLow: 30,
    localDailyCostHigh: 65,
    seasonTags: ["spring", "autumn"],
    popularityScore: 94,
    shortDescription:
      "Mosques, markets, ferries, layered history, and strong value for city travelers.",
  },
  {
    id: "seoul",
    city: "Seoul",
    country: "South Korea",
    countryCode: "KR",
    airportCode: "SEL",
    region: "East Asia",
    latitude: 37.5665,
    longitude: 126.978,
    tags: ["City", "Food", "Culture", "Nightlife"],
    recommendedTripDays: [5, 8],
    stayCostLow: 85,
    stayCostHigh: 150,
    localDailyCostLow: 45,
    localDailyCostHigh: 85,
    seasonTags: ["spring", "autumn"],
    popularityScore: 94,
    shortDescription:
      "Markets, palaces, cafes, K-culture districts, and efficient city transit.",
  },
  {
    id: "singapore",
    city: "Singapore",
    country: "Singapore",
    countryCode: "SG",
    airportCode: "SIN",
    region: "Southeast Asia",
    latitude: 1.3521,
    longitude: 103.8198,
    tags: ["City", "Food", "Family", "Luxury"],
    recommendedTripDays: [3, 5],
    stayCostLow: 115,
    stayCostHigh: 230,
    localDailyCostLow: 60,
    localDailyCostHigh: 115,
    seasonTags: ["year-round"],
    popularityScore: 93,
    shortDescription:
      "A polished city stop with hawker centers, gardens, shopping, and easy logistics.",
  },
  {
    id: "bali",
    city: "Bali",
    country: "Indonesia",
    countryCode: "ID",
    airportCode: "DPS",
    region: "Southeast Asia",
    latitude: -8.3405,
    longitude: 115.092,
    tags: ["Beach", "Nature", "Romantic", "Budget"],
    recommendedTripDays: [5, 10],
    stayCostLow: 45,
    stayCostHigh: 130,
    localDailyCostLow: 28,
    localDailyCostHigh: 65,
    seasonTags: ["dry season", "shoulder"],
    popularityScore: 95,
    shortDescription:
      "Beaches, temples, rice terraces, villas, cafes, and flexible budgets.",
  },
  {
    id: "ho-chi-minh-city",
    city: "Ho Chi Minh City",
    country: "Vietnam",
    countryCode: "VN",
    airportCode: "SGN",
    region: "Southeast Asia",
    latitude: 10.8231,
    longitude: 106.6297,
    tags: ["City", "Food", "Culture", "Budget"],
    recommendedTripDays: [3, 6],
    stayCostLow: 35,
    stayCostHigh: 85,
    localDailyCostLow: 22,
    localDailyCostHigh: 45,
    seasonTags: ["winter", "spring"],
    popularityScore: 90,
    shortDescription:
      "Street food, markets, cafes, museums, and low local costs.",
  },
  {
    id: "dubai",
    city: "Dubai",
    country: "United Arab Emirates",
    countryCode: "AE",
    airportCode: "DXB",
    region: "Middle East",
    latitude: 25.2048,
    longitude: 55.2708,
    tags: ["City", "Luxury", "Family", "Nightlife"],
    recommendedTripDays: [3, 6],
    stayCostLow: 95,
    stayCostHigh: 230,
    localDailyCostLow: 60,
    localDailyCostHigh: 130,
    seasonTags: ["winter"],
    popularityScore: 92,
    shortDescription:
      "Big-city shopping, beaches, desert trips, restaurants, and very easy flight access.",
  },
  {
    id: "marrakesh",
    city: "Marrakesh",
    country: "Morocco",
    countryCode: "MA",
    airportCode: "RAK",
    region: "North Africa",
    latitude: 31.6295,
    longitude: -7.9811,
    tags: ["Culture", "Food", "Romantic", "Budget"],
    recommendedTripDays: [4, 6],
    stayCostLow: 50,
    stayCostHigh: 120,
    localDailyCostLow: 28,
    localDailyCostHigh: 60,
    seasonTags: ["spring", "autumn", "winter"],
    popularityScore: 89,
    shortDescription:
      "Riads, souks, gardens, rooftop dining, and desert-side atmosphere.",
  },
  {
    id: "london",
    city: "London",
    country: "United Kingdom",
    countryCode: "GB",
    airportCode: "LON",
    region: "Europe",
    latitude: 51.5072,
    longitude: -0.1276,
    tags: ["City", "Culture", "Food", "Family"],
    recommendedTripDays: [4, 7],
    stayCostLow: 130,
    stayCostHigh: 240,
    localDailyCostLow: 70,
    localDailyCostHigh: 130,
    seasonTags: ["spring", "summer", "winter"],
    popularityScore: 96,
    shortDescription:
      "Museums, markets, theater, historic neighborhoods, and easy onward rail trips.",
  },
  {
    id: "amsterdam",
    city: "Amsterdam",
    country: "Netherlands",
    countryCode: "NL",
    airportCode: "AMS",
    region: "Europe",
    latitude: 52.3676,
    longitude: 4.9041,
    tags: ["City", "Culture", "Romantic", "Nightlife"],
    recommendedTripDays: [3, 5],
    stayCostLow: 120,
    stayCostHigh: 220,
    localDailyCostLow: 65,
    localDailyCostHigh: 110,
    seasonTags: ["spring", "autumn"],
    popularityScore: 92,
    shortDescription:
      "Canals, museums, cycling, compact neighborhoods, and easy weekend pacing.",
  },
  {
    id: "berlin",
    city: "Berlin",
    country: "Germany",
    countryCode: "DE",
    airportCode: "BER",
    region: "Europe",
    latitude: 52.52,
    longitude: 13.405,
    tags: ["City", "Culture", "Nightlife", "Food"],
    recommendedTripDays: [4, 7],
    stayCostLow: 85,
    stayCostHigh: 160,
    localDailyCostLow: 45,
    localDailyCostHigh: 85,
    seasonTags: ["spring", "summer", "autumn"],
    popularityScore: 91,
    shortDescription:
      "Museums, nightlife, history, parks, and comparatively flexible city costs.",
  },
  {
    id: "prague",
    city: "Prague",
    country: "Czechia",
    countryCode: "CZ",
    airportCode: "PRG",
    region: "Europe",
    latitude: 50.0755,
    longitude: 14.4378,
    tags: ["City", "Culture", "Romantic", "Budget"],
    recommendedTripDays: [3, 5],
    stayCostLow: 65,
    stayCostHigh: 135,
    localDailyCostLow: 35,
    localDailyCostHigh: 70,
    seasonTags: ["spring", "autumn", "winter"],
    popularityScore: 90,
    shortDescription:
      "Historic streets, castles, beer halls, river views, and strong short-break value.",
  },
  {
    id: "budapest",
    city: "Budapest",
    country: "Hungary",
    countryCode: "HU",
    airportCode: "BUD",
    region: "Europe",
    latitude: 47.4979,
    longitude: 19.0402,
    tags: ["City", "Culture", "Nightlife", "Budget"],
    recommendedTripDays: [3, 5],
    stayCostLow: 60,
    stayCostHigh: 125,
    localDailyCostLow: 35,
    localDailyCostHigh: 70,
    seasonTags: ["spring", "autumn", "winter"],
    popularityScore: 90,
    shortDescription:
      "Thermal baths, architecture, ruin bars, river views, and budget-friendly city days.",
  },
  {
    id: "copenhagen",
    city: "Copenhagen",
    country: "Denmark",
    countryCode: "DK",
    airportCode: "CPH",
    region: "Europe",
    latitude: 55.6761,
    longitude: 12.5683,
    tags: ["City", "Food", "Family", "Luxury"],
    recommendedTripDays: [3, 5],
    stayCostLow: 125,
    stayCostHigh: 230,
    localDailyCostLow: 75,
    localDailyCostHigh: 135,
    seasonTags: ["summer", "winter"],
    popularityScore: 86,
    shortDescription:
      "Design, canals, cycling, food halls, and easygoing family-friendly city time.",
  },
  {
    id: "dublin",
    city: "Dublin",
    country: "Ireland",
    countryCode: "IE",
    airportCode: "DUB",
    region: "Europe",
    latitude: 53.3498,
    longitude: -6.2603,
    tags: ["City", "Culture", "Food", "Nightlife"],
    recommendedTripDays: [3, 5],
    stayCostLow: 115,
    stayCostHigh: 220,
    localDailyCostLow: 65,
    localDailyCostHigh: 115,
    seasonTags: ["spring", "summer", "autumn"],
    popularityScore: 87,
    shortDescription:
      "Pubs, literary history, museums, music, and nearby coastal day trips.",
  },
  {
    id: "new-york",
    city: "New York",
    country: "United States",
    countryCode: "US",
    airportCode: "NYC",
    region: "North America",
    latitude: 40.7128,
    longitude: -74.006,
    tags: ["City", "Culture", "Food", "Nightlife"],
    recommendedTripDays: [4, 7],
    stayCostLow: 150,
    stayCostHigh: 280,
    localDailyCostLow: 80,
    localDailyCostHigh: 150,
    seasonTags: ["spring", "autumn", "winter"],
    popularityScore: 97,
    shortDescription:
      "Museums, restaurants, shows, neighborhoods, and nonstop urban energy.",
  },
  {
    id: "miami",
    city: "Miami",
    country: "United States",
    countryCode: "US",
    airportCode: "MIA",
    region: "North America",
    latitude: 25.7617,
    longitude: -80.1918,
    tags: ["Beach", "City", "Food", "Nightlife"],
    recommendedTripDays: [4, 6],
    stayCostLow: 125,
    stayCostHigh: 240,
    localDailyCostLow: 70,
    localDailyCostHigh: 130,
    seasonTags: ["winter", "spring"],
    popularityScore: 90,
    shortDescription:
      "Beaches, art deco blocks, Latin food, nightlife, and warm-weather city breaks.",
  },
  {
    id: "montreal",
    city: "Montreal",
    country: "Canada",
    countryCode: "CA",
    airportCode: "YUL",
    region: "North America",
    latitude: 45.5019,
    longitude: -73.5674,
    tags: ["City", "Culture", "Food", "Budget"],
    recommendedTripDays: [3, 5],
    stayCostLow: 80,
    stayCostHigh: 155,
    localDailyCostLow: 45,
    localDailyCostHigh: 85,
    seasonTags: ["summer", "autumn", "winter"],
    popularityScore: 87,
    shortDescription:
      "French-Canadian food, festivals, old streets, parks, and compact city exploring.",
  },
  {
    id: "vancouver",
    city: "Vancouver",
    country: "Canada",
    countryCode: "CA",
    airportCode: "YVR",
    region: "North America",
    latitude: 49.2827,
    longitude: -123.1207,
    tags: ["City", "Nature", "Adventure", "Food"],
    recommendedTripDays: [4, 7],
    stayCostLow: 115,
    stayCostHigh: 220,
    localDailyCostLow: 60,
    localDailyCostHigh: 115,
    seasonTags: ["summer", "autumn", "winter"],
    popularityScore: 89,
    shortDescription:
      "Mountains, water, neighborhoods, food, and outdoorsy city days.",
  },
  {
    id: "cartagena",
    city: "Cartagena",
    country: "Colombia",
    countryCode: "CO",
    airportCode: "CTG",
    region: "South America",
    latitude: 10.391,
    longitude: -75.4794,
    tags: ["Beach", "Culture", "Romantic", "Budget"],
    recommendedTripDays: [4, 6],
    stayCostLow: 55,
    stayCostHigh: 130,
    localDailyCostLow: 35,
    localDailyCostHigh: 70,
    seasonTags: ["winter", "spring"],
    popularityScore: 87,
    shortDescription:
      "Colorful old-town streets, Caribbean heat, islands, and value-focused stays.",
  },
  {
    id: "medellin",
    city: "Medellin",
    country: "Colombia",
    countryCode: "CO",
    airportCode: "MDE",
    region: "South America",
    latitude: 6.2476,
    longitude: -75.5658,
    tags: ["City", "Nature", "Food", "Budget"],
    recommendedTripDays: [4, 7],
    stayCostLow: 45,
    stayCostHigh: 100,
    localDailyCostLow: 28,
    localDailyCostHigh: 60,
    seasonTags: ["year-round"],
    popularityScore: 88,
    shortDescription:
      "Green city views, cafes, day trips, springlike weather, and moderate costs.",
  },
  {
    id: "buenos-aires",
    city: "Buenos Aires",
    country: "Argentina",
    countryCode: "AR",
    airportCode: "BUE",
    region: "South America",
    latitude: -34.6037,
    longitude: -58.3816,
    tags: ["City", "Culture", "Food", "Nightlife"],
    recommendedTripDays: [5, 8],
    stayCostLow: 60,
    stayCostHigh: 130,
    localDailyCostLow: 35,
    localDailyCostHigh: 75,
    seasonTags: ["spring", "autumn"],
    popularityScore: 89,
    shortDescription:
      "Tango, steak, cafes, bookstores, parks, and late-night city rhythm.",
  },
  {
    id: "lima",
    city: "Lima",
    country: "Peru",
    countryCode: "PE",
    airportCode: "LIM",
    region: "South America",
    latitude: -12.0464,
    longitude: -77.0428,
    tags: ["City", "Food", "Culture", "Budget"],
    recommendedTripDays: [3, 6],
    stayCostLow: 55,
    stayCostHigh: 120,
    localDailyCostLow: 35,
    localDailyCostHigh: 70,
    seasonTags: ["winter", "spring"],
    popularityScore: 86,
    shortDescription:
      "Coastal neighborhoods, museums, markets, and one of the world's best food scenes.",
  },
  {
    id: "santiago",
    city: "Santiago",
    country: "Chile",
    countryCode: "CL",
    airportCode: "SCL",
    region: "South America",
    latitude: -33.4489,
    longitude: -70.6693,
    tags: ["City", "Nature", "Food", "Adventure"],
    recommendedTripDays: [4, 7],
    stayCostLow: 70,
    stayCostHigh: 140,
    localDailyCostLow: 45,
    localDailyCostHigh: 85,
    seasonTags: ["spring", "autumn", "winter"],
    popularityScore: 84,
    shortDescription:
      "Andes views, wine country access, markets, museums, and mountain day trips.",
  },
  {
    id: "cape-town",
    city: "Cape Town",
    country: "South Africa",
    countryCode: "ZA",
    airportCode: "CPT",
    region: "Africa",
    latitude: -33.9249,
    longitude: 18.4241,
    tags: ["Nature", "Beach", "Adventure", "Food"],
    recommendedTripDays: [5, 8],
    stayCostLow: 70,
    stayCostHigh: 160,
    localDailyCostLow: 40,
    localDailyCostHigh: 85,
    seasonTags: ["summer", "spring", "autumn"],
    popularityScore: 91,
    shortDescription:
      "Table Mountain, beaches, wine, food, scenic drives, and high-impact nature.",
  },
  {
    id: "nairobi",
    city: "Nairobi",
    country: "Kenya",
    countryCode: "KE",
    airportCode: "NBO",
    region: "Africa",
    latitude: -1.2921,
    longitude: 36.8219,
    tags: ["Nature", "Adventure", "Culture", "Family"],
    recommendedTripDays: [4, 7],
    stayCostLow: 65,
    stayCostHigh: 155,
    localDailyCostLow: 45,
    localDailyCostHigh: 90,
    seasonTags: ["dry season"],
    popularityScore: 84,
    shortDescription:
      "A practical gateway for wildlife, museums, markets, and nature-focused trips.",
  },
  {
    id: "sydney",
    city: "Sydney",
    country: "Australia",
    countryCode: "AU",
    airportCode: "SYD",
    region: "Oceania",
    latitude: -33.8688,
    longitude: 151.2093,
    tags: ["Beach", "City", "Nature", "Family"],
    recommendedTripDays: [5, 8],
    stayCostLow: 125,
    stayCostHigh: 235,
    localDailyCostLow: 75,
    localDailyCostHigh: 135,
    seasonTags: ["spring", "summer", "autumn"],
    popularityScore: 91,
    shortDescription:
      "Harbor views, beaches, coastal walks, food, and nature within city reach.",
  },
  {
    id: "queenstown",
    city: "Queenstown",
    country: "New Zealand",
    countryCode: "NZ",
    airportCode: "ZQN",
    region: "Oceania",
    latitude: -45.0312,
    longitude: 168.6626,
    tags: ["Nature", "Adventure", "Romantic", "Luxury"],
    recommendedTripDays: [5, 8],
    stayCostLow: 120,
    stayCostHigh: 240,
    localDailyCostLow: 80,
    localDailyCostHigh: 150,
    seasonTags: ["summer", "winter"],
    popularityScore: 86,
    shortDescription:
      "Alpine scenery, lakes, hikes, adventure activities, and scenic drives.",
  },
  {
    id: "maldives",
    city: "Male",
    country: "Maldives",
    countryCode: "MV",
    airportCode: "MLE",
    region: "Indian Ocean",
    latitude: 4.1755,
    longitude: 73.5093,
    tags: ["Beach", "Romantic", "Luxury", "Family"],
    recommendedTripDays: [4, 7],
    stayCostLow: 130,
    stayCostHigh: 360,
    localDailyCostLow: 65,
    localDailyCostHigh: 150,
    seasonTags: ["winter", "spring"],
    popularityScore: 89,
    shortDescription:
      "Island resorts, clear water, snorkeling, and short high-value beach escapes.",
  },
];

export const destinations: Destination[] = destinationRecords.map(
  (destination) => ({
    ...destination,
    image: `/destinations/${destination.id}.webp`,
    imageAlt: `${destination.city}, ${destination.country} travel photography`,
    imageCredit: "Photo via Unsplash",
  }),
);

const officialSources = {
  ukAdvice: "https://www.gov.uk/foreign-travel-advice",
  japanMofa: "https://www.mofa.go.jp/j_info/visit/visa/short/novisa.html",
  indiaMea: "https://www.mea.gov.in/VFFIN.htm",
  thailandDelhi:
    "https://newdelhi.thaiembassy.org/en/content/latest-update-on-revision-to-thailand-s-visa-exemp",
  euEtias: "https://travel-europe.europa.eu/etias_en",
};

export const visaRules: VisaRule[] = [
  ...[
    "JP",
    "TH",
    "MX",
    "PT",
    "ES",
    "IT",
    "FR",
    "GR",
    "TR",
    "KR",
    "SG",
    "ID",
    "VN",
    "AE",
    "MA",
    "NL",
    "DE",
    "CZ",
    "HU",
    "DK",
    "IE",
    "US",
    "CA",
    "CO",
    "AR",
    "PE",
    "CL",
    "ZA",
    "KE",
    "AU",
    "NZ",
    "MV",
  ].map((countryCode) => ({
    passportCountry: "UK" as const,
    destinationCountryCode: countryCode,
    status:
      countryCode === "US" ||
      countryCode === "CA" ||
      countryCode === "AU" ||
      countryCode === "NZ" ||
      countryCode === "KE"
        ? ("eta" as const)
        : countryCode === "VN"
          ? ("evisa" as const)
          : ("visa_free" as const),
    maxStayDays:
      countryCode === "TH"
        ? 60
        : countryCode === "SG" || countryCode === "AE"
          ? 30
          : countryCode === "US"
            ? 90
            : null,
    officialSourceUrl:
      countryCode === "JP"
        ? officialSources.japanMofa
        : countryCode === "TH"
          ? "https://www.gov.uk/foreign-travel-advice/thailand/entry-requirements"
          : countryCode === "US"
            ? "https://esta.cbp.dhs.gov/"
            : countryCode === "CA"
              ? "https://www.canada.ca/en/immigration-refugees-citizenship/services/visit-canada/eta.html"
              : countryCode === "AU"
                ? "https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/evisitor-651"
                : countryCode === "NZ"
                  ? "https://www.immigration.govt.nz/new-zealand-visas/visas/visa/nzeta"
                  : countryCode === "KE"
                    ? "https://www.etakenya.go.ke/"
                    : `${officialSources.ukAdvice}/${countryCode.toLowerCase()}`,
    lastVerifiedAt: "2026-08-17",
  })),
  ...[
    { code: "TH", status: "visa_free", days: 30, source: officialSources.thailandDelhi },
    { code: "ID", status: "visa_on_arrival", days: 30, source: officialSources.indiaMea },
    { code: "MV", status: "visa_on_arrival", days: 30, source: officialSources.indiaMea },
    { code: "JP", status: "evisa", days: 90, source: officialSources.indiaMea },
    { code: "SG", status: "evisa", days: 30, source: officialSources.indiaMea },
    { code: "VN", status: "evisa", days: 30, source: officialSources.indiaMea },
    { code: "AE", status: "evisa", days: null, source: officialSources.indiaMea },
    { code: "TR", status: "evisa", days: 30, source: officialSources.indiaMea },
    { code: "KE", status: "eta", days: null, source: officialSources.indiaMea },
    { code: "MA", status: "evisa", days: null, source: officialSources.indiaMea },
    { code: "AR", status: "evisa", days: null, source: officialSources.indiaMea },
    { code: "NZ", status: "evisa", days: null, source: officialSources.indiaMea },
    { code: "US", status: "visa_required", days: null, source: "https://travel.state.gov/content/travel/en/us-visas/tourism-visit/visitor.html" },
    { code: "GB", status: "visa_required", days: null, source: "https://www.gov.uk/check-uk-visa" },
    { code: "CA", status: "visa_required", days: null, source: "https://www.canada.ca/en/immigration-refugees-citizenship/services/visit-canada.html" },
    { code: "PT", status: "visa_required", days: null, source: officialSources.euEtias },
    { code: "ES", status: "visa_required", days: null, source: officialSources.euEtias },
    { code: "IT", status: "visa_required", days: null, source: officialSources.euEtias },
    { code: "FR", status: "visa_required", days: null, source: officialSources.euEtias },
    { code: "GR", status: "visa_required", days: null, source: officialSources.euEtias },
    { code: "NL", status: "visa_required", days: null, source: officialSources.euEtias },
    { code: "DE", status: "visa_required", days: null, source: officialSources.euEtias },
    { code: "CZ", status: "visa_required", days: null, source: officialSources.euEtias },
    { code: "HU", status: "visa_required", days: null, source: officialSources.euEtias },
    { code: "DK", status: "visa_required", days: null, source: officialSources.euEtias },
    { code: "IE", status: "visa_required", days: null, source: "https://www.irishimmigration.ie/coming-to-visit-ireland/" },
  ].map((rule) => ({
    passportCountry: "India" as const,
    destinationCountryCode: rule.code,
    status: rule.status as VisaStatus,
    maxStayDays: rule.days,
    officialSourceUrl: rule.source,
    lastVerifiedAt: "2026-08-17",
  })),
];

export const flightCache: FlightCache[] = [
  ["New York", "MEX", 240, 330],
  ["New York", "CUN", 260, 380],
  ["New York", "LIS", 430, 620],
  ["New York", "PAR", 480, 680],
  ["New York", "LON", 430, 650],
  ["New York", "YUL", 170, 260],
  ["New York", "CTG", 300, 470],
  ["New York", "MDE", 330, 500],
  ["New York", "BUE", 620, 880],
  ["New York", "DUB", 420, 620],
  ["London", "LIS", 95, 180],
  ["London", "BCN", 85, 170],
  ["London", "ROM", 110, 210],
  ["London", "ATH", 135, 260],
  ["London", "IST", 150, 280],
  ["London", "RAK", 120, 240],
  ["London", "BUD", 80, 160],
  ["London", "PRG", 75, 155],
  ["London", "BER", 85, 165],
  ["London", "AMS", 80, 150],
  ["Delhi", "BKK", 190, 310],
  ["Delhi", "DPS", 260, 430],
  ["Delhi", "SGN", 230, 380],
  ["Delhi", "DXB", 210, 360],
  ["Delhi", "SIN", 230, 390],
  ["Delhi", "MLE", 210, 340],
  ["Delhi", "TYO", 470, 720],
  ["Delhi", "IST", 360, 560],
  ["Delhi", "NBO", 390, 640],
  ["Mumbai", "DXB", 160, 280],
  ["Mumbai", "BKK", 210, 340],
  ["Mumbai", "DPS", 280, 460],
  ["Mumbai", "SIN", 240, 390],
  ["Mumbai", "MLE", 190, 320],
  ["Mumbai", "IST", 380, 590],
  ["Toronto", "YUL", 140, 230],
  ["Toronto", "NYC", 190, 310],
  ["Toronto", "MEX", 340, 520],
  ["Toronto", "CUN", 320, 480],
  ["Toronto", "LIS", 520, 760],
  ["Toronto", "LON", 560, 780],
  ["Sydney", "DPS", 310, 520],
  ["Sydney", "SIN", 350, 590],
  ["Sydney", "TYO", 530, 820],
  ["Sydney", "ZQN", 270, 460],
  ["Sydney", "AKL", 240, 390],
].map(([origin, destinationAirportCode, low, high]) => ({
  origin: String(origin),
  destinationAirportCode: String(destinationAirportCode),
  low: Number(low),
  high: Number(high),
  cachedAt: "2026-08-01",
}));

export const popularDestinationIds = [
  "bangkok",
  "mexico-city",
  "lisbon",
  "tokyo",
  "bali",
  "istanbul",
  "paris",
  "cape-town",
];
